apiVersion: v1
kind: Service

metadata:
  name: enterprise-devops-service
  namespace: enterprise-devops

spec:
  selector:
    app: enterprise-devops-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP
